FROM python:3.7-slim

COPY utils/debian/sources.list.buster /etc/apt/sources.list

RUN rm -rvf /etc/apt/sources.list.d

# RUN apt-get update && apt-get install vim libpython3.7-dev  python-psutil postgresql-server-dev-10 libgtk2.0-dev libgtk-3-dev

# RUN pip install --index-url http://internal-mirrors.cloudwalk.work:8081/repository/pypi-group/simple --trusted-host  internal-mirrors.cloudwalk.work cook==1.0.0

